### ISSUE TITLE
Fully specified lattice

### ISSUE THREAD

**Issue by alexis-ji** [arekfu/t4_geom_convert#16]
Handle fully specified lattice. 
See example attached. 
[lattice_mcnp_fill_example.txt](https://github.com/arekfu/t4_geom_convert/files/3697761/lattice_mcnp_fill_example.txt)

![snapshot1](https://user-images.githubusercontent.com/56262648/66318596-ea8cde00-e91b-11e9-9b68-a3f85cd6ad75.png)
![snapshot2](https://user-images.githubusercontent.com/56262648/66318598-ea8cde00-e91b-11e9-9b4e-ef2d33f4bc66.png)

**Comment by arekfu** [comment]
Great, thank you Alexis!
